import { sql } from 'drizzle-orm'
import {
  customType,
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

import { TODO_STATUSES } from '#/lib/todo.ts'

// postgres full-text search type; drizzle has no first-class tsvector
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'tsvector'
  },
})

export const todoStatus = pgEnum('todo_status', TODO_STATUSES)

export const todos = pgTable(
  'todos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: text('title').notNull(),
    description: text('description').notNull().default(''),
    status: todoStatus('status').notNull().default('todo'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    // set by the server when a todo enters done, cleared when it leaves
    completedAt: timestamp('completed_at', { withTimezone: true }),
    // soft delete marker; null means live, which is what every list query filters on
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    // generated by postgres so it can never drift from title/description
    searchVector: tsvector('search_vector').generatedAlwaysAs(
      sql`to_tsvector('english', title || ' ' || description)`,
    ),
  },
  (table) => [
    index('todos_status_created_idx')
      .on(table.status, table.createdAt.desc())
      .where(sql`deleted_at is null`),
    index('todos_live_created_idx')
      .on(table.createdAt.desc())
      .where(sql`deleted_at is null`),
    index('todos_search_idx').using('gin', table.searchVector),
  ],
)

export type Todo = typeof todos.$inferSelect
export type NewTodo = typeof todos.$inferInsert
